# Rule All
rule all:
    input:
        "reverse_complement.txt"

# Rule to convert RNA to DNA
rule convert_rna_to_dna:
    input:
        "rna_sequences.txt"
    output:
        "dna_sequences.txt"
    shell:
        # tr is a command line tool to translate characters, here it converts U's to T's
        "tr 'U' 'T' < {input} > {output}"

# Rule to find reverse complement of DNA
rule reverse_complement_dna:
    input:
        "dna_sequences.txt"
    output:
        "reverse_complement.txt"
    shell:
        # rev is a command line tool to reverse lines of a file
        "rev {input} | tr 'ATCG' 'TAGC' > {output}"
 