
SAMPLE="2982B"

fastq_dir="../../../data/fastq"


# Rule All
rule all:
    input:
        r1=fastq_dir + "/" + SAMPLE + "_trim_1.fastq.gz",
        r2=fastq_dir + "/" + SAMPLE + "_trim_2.fastq.gz"

# Rule to collect all reverse complements into one file
rule fastp:
    input:
        r1=fastq_dir + "/" + SAMPLE + "_1.fastq.gz",
        r2=fastq_dir + "/" + SAMPLE + "_2.fastq.gz"
    output:
        r1=fastq_dir + "/" + SAMPLE + "_trim_1.fastq.gz",
        r2=fastq_dir + "/" + SAMPLE + "_trim_2.fastq.gz"
    threads: 6
    shell:
        """
        fastp --in1 {input.r1} --in2 {input.r2} \
        --out1 {output.r1} --out2 {output.r2} \
        --thread {threads} \
        --detect_adapter_for_pe 
        """
